"""Config defaults registry — single source of truth for all tunable parameters.

Each parameter is defined with its key, default value, type, constraints, and
UI metadata. On startup, seed_config_defaults() inserts any missing keys using
INSERT OR IGNORE, preserving user overrides.
"""

from typing import Any

CONFIG_DEFAULTS: list[dict[str, Any]] = [
    # ── Activity Monitor ──────────────────────────────────────────────
    {
        "key": "activity.daily_snapshot_cap",
        "default_value": "20",
        "value_type": "number",
        "label": "Daily Snapshot Cap",
        "description": "Maximum adaptive snapshots triggered per day.",
        "category": "Activity Monitor",
        "min_value": 5,
        "max_value": 100,
        "step": 1,
    },
    {
        "key": "activity.snapshot_cooldown_s",
        "default_value": "1800",
        "value_type": "number",
        "label": "Snapshot Cooldown (s)",
        "description": "Minimum seconds between adaptive snapshots.",
        "category": "Activity Monitor",
        "min_value": 300,
        "max_value": 7200,
        "step": 60,
    },
    {
        "key": "activity.flush_interval_s",
        "default_value": "900",
        "value_type": "number",
        "label": "Flush Interval (s)",
        "description": "How often buffered events are flushed to cache windows.",
        "category": "Activity Monitor",
        "min_value": 60,
        "max_value": 3600,
        "step": 60,
    },
    {
        "key": "activity.max_window_age_h",
        "default_value": "24",
        "value_type": "number",
        "label": "Max Window Age (h)",
        "description": "Rolling window retention in hours.",
        "category": "Activity Monitor",
        "min_value": 6,
        "max_value": 168,
        "step": 1,
    },
    # ── Feature Engineering ───────────────────────────────────────────
    {
        "key": "features.decay_half_life_days",
        "default_value": "7",
        "value_type": "number",
        "label": "Decay Half-Life (days)",
        "description": "Exponential decay half-life for training sample recency weighting.",
        "category": "Feature Engineering",
        "min_value": 1,
        "max_value": 30,
        "step": 1,
    },
    {
        "key": "features.weekday_alignment_bonus",
        "default_value": "1.5",
        "value_type": "number",
        "label": "Weekday Alignment Bonus",
        "description": "Multiplier for training samples from the same day of week.",
        "category": "Feature Engineering",
        "min_value": 1.0,
        "max_value": 3.0,
        "step": 0.1,
    },
    # ── Shadow Engine ─────────────────────────────────────────────────
    {
        "key": "shadow.min_confidence",
        "default_value": "0.3",
        "value_type": "number",
        "label": "Min Confidence",
        "description": "Predictions below this confidence are not stored.",
        "category": "Shadow Engine",
        "min_value": 0.05,
        "max_value": 0.9,
        "step": 0.05,
    },
    {
        "key": "shadow.default_window_seconds",
        "default_value": "600",
        "value_type": "number",
        "label": "Default Window (s)",
        "description": "Evaluation window for predictions in seconds.",
        "category": "Shadow Engine",
        "min_value": 60,
        "max_value": 3600,
        "step": 30,
    },
    {
        "key": "shadow.resolution_interval_s",
        "default_value": "60",
        "value_type": "number",
        "label": "Resolution Interval (s)",
        "description": "How often expired prediction windows are resolved.",
        "category": "Shadow Engine",
        "min_value": 10,
        "max_value": 300,
        "step": 10,
    },
    {
        "key": "shadow.prediction_cooldown_s",
        "default_value": "30",
        "value_type": "number",
        "label": "Prediction Cooldown (s)",
        "description": "Minimum seconds between prediction attempts (debounce).",
        "category": "Shadow Engine",
        "min_value": 5,
        "max_value": 300,
        "step": 5,
    },
    {
        "key": "shadow.explore_strategy",
        "default_value": "thompson",
        "value_type": "select",
        "label": "Explore Strategy",
        "description": "Exploration strategy for shadow predictions: Thompson Sampling or epsilon-greedy.",
        "category": "Shadow Engine",
        "options": "thompson,epsilon",
    },
    {
        "key": "shadow.thompson_discount_factor",
        "default_value": "0.95",
        "value_type": "number",
        "label": "Thompson Discount Factor",
        "description": "f-dsw discount factor for Thompson Sampling posteriors (lower = faster adaptation).",
        "category": "Shadow Engine",
        "min_value": 0.8,
        "max_value": 1.0,
        "step": 0.01,
    },
    {
        "key": "shadow.thompson_window_size",
        "default_value": "100",
        "value_type": "number",
        "label": "Thompson Window Size",
        "description": "Maximum effective history length for Thompson Sampling buckets.",
        "category": "Shadow Engine",
        "min_value": 20,
        "max_value": 500,
        "step": 10,
    },
    # ── Data Quality ──────────────────────────────────────────────────
    {
        "key": "curation.auto_exclude_domains",
        "default_value": (
            "update,tts,stt,scene,button,number,select,input_boolean,input_number,"
            "input_select,input_text,input_datetime,counter,script,zone,sun,weather,"
            "conversation,event,automation,camera,image,remote"
        ),
        "value_type": "string",
        "label": "Auto-Exclude Domains",
        "description": "Comma-separated domains automatically excluded from curation.",
        "category": "Data Quality",
    },
    {
        "key": "curation.noise_event_threshold",
        "default_value": "1000",
        "value_type": "number",
        "label": "Noise Event Threshold",
        "description": "Daily event count above which an entity is considered noise (if low state variety).",
        "category": "Data Quality",
        "min_value": 100,
        "max_value": 10000,
        "step": 100,
    },
    {
        "key": "curation.stale_days_threshold",
        "default_value": "30",
        "value_type": "number",
        "label": "Stale Days Threshold",
        "description": "Entities with no state changes in this many days are auto-excluded.",
        "category": "Data Quality",
        "min_value": 7,
        "max_value": 90,
        "step": 1,
    },
    {
        "key": "curation.unavailable_grace_hours",
        "default_value": "0",
        "value_type": "number",
        "label": "Unavailable Grace Hours",
        "description": "Entities unavailable longer than this are auto-excluded. 0 = disabled.",
        "category": "Data Quality",
        "min_value": 0,
        "max_value": 168,
        "step": 1,
    },
    {
        "key": "curation.vehicle_patterns",
        "default_value": "tesla,luda,tessy,vehicle,car_",
        "value_type": "string",
        "label": "Vehicle Patterns",
        "description": "Comma-separated patterns to match vehicle-related entity names.",
        "category": "Data Quality",
    },
    # ── Anomaly Detection ──────────────────────────────────────────────
    {
        "key": "anomaly.use_autoencoder",
        "default_value": "true",
        "value_type": "boolean",
        "label": "Use Autoencoder",
        "description": "Enable hybrid autoencoder + IsolationForest anomaly detection.",
        "category": "Anomaly Detection",
    },
    {
        "key": "anomaly.ae_hidden_layers",
        "default_value": "24,12,24",
        "value_type": "string",
        "label": "Autoencoder Hidden Layers",
        "description": "Comma-separated hidden layer sizes for the autoencoder (e.g. 24,12,24).",
        "category": "Anomaly Detection",
    },
    {
        "key": "anomaly.ae_max_iter",
        "default_value": "200",
        "value_type": "number",
        "label": "Autoencoder Max Iterations",
        "description": "Maximum training iterations for the autoencoder.",
        "category": "Anomaly Detection",
        "min_value": 50,
        "max_value": 1000,
        "step": 50,
    },
    {
        "key": "anomaly.contamination",
        "default_value": "0.05",
        "value_type": "number",
        "label": "Contamination Factor",
        "description": "Expected proportion of anomalies in the dataset.",
        "category": "Anomaly Detection",
        "min_value": 0.01,
        "max_value": 0.20,
        "step": 0.01,
    },
    # ── Forecaster ─────────────────────────────────────────────────────
    {
        "key": "forecaster.backend",
        "default_value": "auto",
        "value_type": "select",
        "label": "Forecaster Backend",
        "description": "Which forecasting backend to use. 'auto' prefers NeuralProphet, falls back to Prophet.",
        "category": "Forecaster",
        "options": "auto,neuralprophet,prophet",
    },
    {
        "key": "forecaster.epochs",
        "default_value": "100",
        "value_type": "number",
        "label": "Training Epochs",
        "description": "Number of training epochs for NeuralProphet (ignored by Prophet).",
        "category": "Forecaster",
        "min_value": 10,
        "max_value": 500,
        "step": 10,
    },
    {
        "key": "forecaster.learning_rate",
        "default_value": "0.1",
        "value_type": "number",
        "label": "Learning Rate",
        "description": "Optimizer learning rate for NeuralProphet (ignored by Prophet).",
        "category": "Forecaster",
        "min_value": 0.001,
        "max_value": 1.0,
        "step": 0.01,
    },
    {
        "key": "forecaster.ar_order",
        "default_value": "7",
        "value_type": "number",
        "label": "AR Order",
        "description": "Number of autoregression lags for NeuralProphet (7 = one week of history).",
        "category": "Forecaster",
        "min_value": 1,
        "max_value": 30,
        "step": 1,
    },
    # ── Drift Detection ─────────────────────────────────────────────
    {
        "key": "drift.adwin_delta",
        "default_value": "0.002",
        "value_type": "number",
        "label": "ADWIN Delta",
        "description": "ADWIN confidence parameter. Lower values reduce false positives but slow detection.",
        "category": "Drift Detection",
        "min_value": 0.0001,
        "max_value": 0.1,
        "step": 0.001,
    },
    {
        "key": "drift.require_confirmation",
        "default_value": "false",
        "value_type": "boolean",
        "label": "Require Confirmation",
        "description": "When true, drift must be confirmed by multiple detectors before triggering retrain.",
        "category": "Drift Detection",
    },
    {
        "key": "drift.page_hinkley_enabled",
        "default_value": "true",
        "value_type": "boolean",
        "label": "Page-Hinkley Enabled",
        "description": "Whether to run Page-Hinkley drift detection alongside threshold checks.",
        "category": "Drift Detection",
    },
    # ── Reference Model ────────────────────────────────────────────────
    {
        "key": "reference_model.enabled",
        "default_value": "true",
        "value_type": "boolean",
        "label": "Reference Model Enabled",
        "description": "Enable clean reference model for distinguishing meta-learner errors from behavioral drift.",
        "category": "Reference Model",
    },
    {
        "key": "reference_model.comparison_window_days",
        "default_value": "7",
        "value_type": "number",
        "label": "Comparison Window (days)",
        "description": "Number of days of accuracy history to compare between primary and reference models.",
        "category": "Reference Model",
        "min_value": 3,
        "max_value": 30,
        "step": 1,
    },
    {
        "key": "reference_model.alert_threshold_pct",
        "default_value": "5.0",
        "value_type": "number",
        "label": "Alert Threshold (%)",
        "description": "Minimum accuracy divergence percentage to trigger a meta-learner error alert.",
        "category": "Reference Model",
        "min_value": 1.0,
        "max_value": 20.0,
        "step": 0.5,
    },
    # ── Feature Selection ──────────────────────────────────────────────
    {
        "key": "feature_selection.enabled",
        "default_value": "true",
        "value_type": "boolean",
        "label": "Feature Selection Enabled",
        "description": "Enable automatic feature selection before model training.",
        "category": "Feature Selection",
    },
    {
        "key": "feature_selection.method",
        "default_value": "mrmr",
        "value_type": "select",
        "label": "Selection Method",
        "description": "Feature selection algorithm: mRMR, importance-based, or none.",
        "category": "Feature Selection",
        "options": "mrmr,importance,none",
    },
    {
        "key": "feature_selection.max_features",
        "default_value": "30",
        "value_type": "number",
        "label": "Max Features",
        "description": "Maximum number of features to retain after selection.",
        "category": "Feature Selection",
        "min_value": 10,
        "max_value": 48,
        "step": 1,
    },
    {
        "key": "feature_selection.recompute_interval_days",
        "default_value": "7",
        "value_type": "number",
        "label": "Recompute Interval (days)",
        "description": "How often to recompute the selected feature set.",
        "category": "Feature Selection",
        "min_value": 1,
        "max_value": 30,
        "step": 1,
    },
    # ── Narration ─────────────────────────────────────────────────────
    {
        "key": "narration.use_shap",
        "default_value": "true",
        "value_type": "boolean",
        "label": "Use SHAP",
        "description": "Ground LLM narration in SHAP feature attributions for faithful explanations.",
        "category": "Narration",
    },
    {
        "key": "narration.top_features",
        "default_value": "5",
        "value_type": "number",
        "label": "Top Features",
        "description": "Number of top SHAP contributors to include in narration.",
        "category": "Narration",
        "min_value": 3,
        "max_value": 10,
        "step": 1,
    },
    {
        "key": "narration.grounding_mode",
        "default_value": "shap",
        "value_type": "select",
        "label": "Grounding Mode",
        "description": "Source for feature attribution: SHAP values, built-in importance, or none.",
        "category": "Narration",
        "options": "shap,importance,none",
    },
    # ── Incremental Training ──────────────────────────────────────────
    {
        "key": "incremental.enabled",
        "default_value": "true",
        "value_type": "boolean",
        "label": "Incremental Training Enabled",
        "description": "Enable eGBDT incremental LightGBM adaptation on drift detection.",
        "category": "Incremental Training",
    },
    {
        "key": "incremental.boost_rounds",
        "default_value": "20",
        "value_type": "number",
        "label": "Boost Rounds",
        "description": "Number of boosting rounds to add during incremental training.",
        "category": "Incremental Training",
        "min_value": 5,
        "max_value": 100,
        "step": 5,
    },
    {
        "key": "incremental.max_total_trees",
        "default_value": "500",
        "value_type": "number",
        "label": "Max Total Trees",
        "description": "Maximum tree count before forcing a full retrain.",
        "category": "Incremental Training",
        "min_value": 100,
        "max_value": 2000,
        "step": 100,
    },
    {
        "key": "incremental.data_window_days",
        "default_value": "14",
        "value_type": "number",
        "label": "Data Window (days)",
        "description": "Number of recent days of data used for incremental training.",
        "category": "Incremental Training",
        "min_value": 7,
        "max_value": 30,
        "step": 1,
    },
    # ── Presence Tracking ─────────────────────────────────────────────
    {
        "key": "presence.mqtt_host",
        "default_value": "192.168.1.35",
        "value_type": "string",
        "label": "MQTT Host",
        "description": "Hostname or IP of the MQTT broker (Mosquitto on HA).",
        "category": "Presence Tracking",
    },
    {
        "key": "presence.mqtt_port",
        "default_value": "1883",
        "value_type": "number",
        "label": "MQTT Port",
        "description": "Port of the MQTT broker.",
        "category": "Presence Tracking",
        "min_value": 1,
        "max_value": 65535,
        "step": 1,
    },
    {
        "key": "presence.mqtt_user",
        "default_value": "frigate",
        "value_type": "string",
        "label": "MQTT User",
        "description": "Username for MQTT broker authentication.",
        "category": "Presence Tracking",
    },
    {
        "key": "presence.mqtt_password",
        "default_value": "",
        "value_type": "string",
        "label": "MQTT Password",
        "description": "Password for MQTT broker authentication.",
        "category": "Presence Tracking",
    },
    {
        "key": "presence.camera_rooms",
        "default_value": "",
        "value_type": "string",
        "label": "Camera-to-Room Mapping",
        "description": (
            "Comma-separated camera:room pairs"
            " (e.g. driveway:driveway,carters_room:carters_room). Leave empty for defaults."
        ),
        "category": "Presence Tracking",
    },
    # ── Correction Propagation ─────────────────────────────────────────
    {
        "key": "propagation.enabled",
        "default_value": "true",
        "value_type": "boolean",
        "label": "Propagation Enabled",
        "description": "Enable adaptive correction propagation (Slivkins zooming + replay).",
        "category": "Correction Propagation",
    },
    {
        "key": "propagation.base_radius_hours",
        "default_value": "1.0",
        "value_type": "number",
        "label": "Base Radius (hours)",
        "description": "Base temporal radius for correction propagation before adaptive narrowing.",
        "category": "Correction Propagation",
        "min_value": 0.25,
        "max_value": 4.0,
        "step": 0.25,
    },
    {
        "key": "propagation.min_observations_for_narrow",
        "default_value": "10",
        "value_type": "number",
        "label": "Min Observations to Narrow",
        "description": "Minimum observations in a context cell before radius begins narrowing.",
        "category": "Correction Propagation",
        "min_value": 5,
        "max_value": 50,
        "step": 5,
    },
    {
        "key": "propagation.kernel_bandwidth",
        "default_value": "0.5",
        "value_type": "number",
        "label": "Kernel Bandwidth",
        "description": "Gaussian kernel bandwidth for context similarity weighting.",
        "category": "Correction Propagation",
        "min_value": 0.1,
        "max_value": 2.0,
        "step": 0.1,
    },
    {
        "key": "propagation.replay_buffer_size",
        "default_value": "200",
        "value_type": "number",
        "label": "Replay Buffer Size",
        "description": "Maximum entries in the prioritized experience replay buffer.",
        "category": "Correction Propagation",
        "min_value": 50,
        "max_value": 1000,
        "step": 50,
    },
    {
        "key": "propagation.replay_alpha",
        "default_value": "0.6",
        "value_type": "number",
        "label": "Replay Alpha",
        "description": "Prioritization exponent for replay sampling (0=uniform, 1=fully prioritized).",
        "category": "Correction Propagation",
        "min_value": 0.0,
        "max_value": 1.0,
        "step": 0.1,
    },
    {
        "key": "propagation.max_propagations_per_score",
        "default_value": "5",
        "value_type": "number",
        "label": "Max Propagations per Score",
        "description": "Maximum number of nearby contexts to propagate each correction to.",
        "category": "Correction Propagation",
        "min_value": 1,
        "max_value": 20,
        "step": 1,
    },
]


async def seed_config_defaults(cache) -> int:
    """Seed all config defaults into the database.

    Uses INSERT OR IGNORE so existing user overrides are preserved.

    Args:
        cache: CacheManager instance (must be initialized).

    Returns:
        Number of new parameters inserted.
    """
    inserted = 0
    for param in CONFIG_DEFAULTS:
        was_inserted = await cache.upsert_config_default(
            key=param["key"],
            default_value=param["default_value"],
            value_type=param["value_type"],
            label=param.get("label", ""),
            description=param.get("description", ""),
            category=param.get("category", ""),
            min_value=param.get("min_value"),
            max_value=param.get("max_value"),
            options=param.get("options"),
            step=param.get("step"),
        )
        if was_inserted:
            inserted += 1
    return inserted
