"""Engine capability declarations.

Each Capability describes a batch engine command — its dependencies, config keys,
test paths, and systemd units. These are collected by
CapabilityRegistry.collect_from_modules() alongside the hub module declarations.
"""

from aria.capabilities import Capability

ENGINE_CAPABILITIES = [
    Capability(
        id="snapshot",
        name="Daily State Snapshot",
        description="Collects current HA state into a structured snapshot for downstream analysis.",
        module="engine.snapshot",
        layer="engine",
        test_paths=["tests/engine/test_collectors.py"],
        status="stable",
        added_version="1.0.0",
        depends_on=[],
    ),
    Capability(
        id="predictions",
        name="Prediction Generation",
        description="Generates predictions from the latest snapshot using trained ML models.",
        module="engine.predictions",
        layer="engine",
        test_paths=["tests/engine/test_predictions.py"],
        status="stable",
        added_version="1.0.0",
        depends_on=["snapshot"],
    ),
    Capability(
        id="scoring",
        name="Prediction Scoring",
        description="Scores yesterday's predictions against actual outcomes.",
        module="engine.predictions",
        layer="engine",
        test_paths=["tests/engine/test_predictions.py"],
        status="stable",
        added_version="1.0.0",
        depends_on=["predictions"],
    ),
    Capability(
        id="model_training",
        name="ML Model Training",
        description="Trains GradientBoosting, RandomForest, and LightGBM models from accumulated data.",
        module="engine.models",
        layer="engine",
        test_paths=["tests/engine/test_models.py"],
        status="stable",
        added_version="1.0.0",
        depends_on=["snapshot"],
    ),
    Capability(
        id="meta_learning",
        name="LLM Meta-Learning",
        description="Uses Ollama LLM to analyze model performance and tune feature configuration.",
        module="engine.llm",
        layer="engine",
        test_paths=["tests/engine/test_llm.py", "tests/integration/test_meta_learning.py"],
        status="stable",
        added_version="1.0.0",
        depends_on=["model_training"],
    ),
    Capability(
        id="drift_detection",
        name="Concept Drift Detection",
        description="Detects concept drift in prediction accuracy using ADWIN and Page-Hinkley.",
        module="engine.analysis",
        layer="engine",
        test_paths=["tests/engine/test_drift.py"],
        status="stable",
        added_version="1.0.0",
        depends_on=["scoring"],
    ),
    Capability(
        id="correlations",
        name="Entity Correlations",
        description="Computes entity co-occurrence correlation matrices from logbook data.",
        module="engine.analysis",
        layer="engine",
        test_paths=["tests/engine/test_entity_correlations.py"],
        status="stable",
        added_version="1.0.0",
        depends_on=[],
    ),
    Capability(
        id="sequence_training",
        name="Sequence Model Training",
        description="Trains Markov chain models from logbook event sequences.",
        module="engine.analysis",
        layer="engine",
        test_paths=["tests/engine/test_sequence_anomalies.py"],
        status="stable",
        added_version="1.0.0",
        depends_on=[],
    ),
    Capability(
        id="sequence_anomalies",
        name="Sequence Anomaly Detection",
        description="Detects anomalous event sequences using trained Markov chain models.",
        module="engine.analysis",
        layer="engine",
        test_paths=["tests/engine/test_sequence_anomalies.py"],
        status="stable",
        added_version="1.0.0",
        depends_on=["sequence_training"],
    ),
    Capability(
        id="automation_suggestions",
        name="LLM Automation Suggestions",
        description="Generates HA automation YAML from entity correlations via Ollama LLM.",
        module="engine.llm",
        layer="engine",
        test_paths=["tests/engine/test_automation_suggestions.py"],
        status="stable",
        added_version="1.0.0",
        depends_on=["correlations"],
    ),
    Capability(
        id="prophet_forecasting",
        name="Prophet Seasonal Forecasting",
        description="Trains Prophet/NeuralProphet seasonal forecasters for time-series metrics.",
        module="engine.models",
        layer="engine",
        test_paths=["tests/engine/test_prophet.py"],
        optional_deps=["prophet"],
        status="stable",
        added_version="1.0.0",
        depends_on=["snapshot"],
    ),
    Capability(
        id="occupancy_estimation",
        name="Bayesian Occupancy Estimation",
        description="Estimates home occupancy probability using Bayesian inference on sensor data.",
        module="engine.analysis",
        layer="engine",
        test_paths=["tests/engine/test_occupancy.py"],
        status="stable",
        added_version="1.0.0",
        depends_on=["snapshot"],
    ),
    Capability(
        id="power_profiling",
        name="Appliance Power Profiling",
        description="Analyzes per-outlet power consumption patterns and profiles appliance usage.",
        module="engine.analysis",
        layer="engine",
        test_paths=["tests/engine/test_power_profiles.py"],
        status="stable",
        added_version="1.0.0",
        depends_on=["snapshot"],
    ),
]
